### PR TITLE
do the funni brian damage text

### PR DESCRIPTION
**Pull request by SufferingSevereBrianDamage**
yesyesfast

### CODE REVIEW

**Comment by Lisenaaaa** [comment]
no

**Comment by SufferingSevereBrianDamage** [comment]
your mother

**Comment by SufferingSevereBrianDamage** [comment]
i am going to eat your door

**Comment by SufferingSevereBrianDamage** [comment]
yes

**Comment by SufferingSevereBrianDamage** [comment]
<:widew:880736643454210048>

**Comment by SufferingSevereBrianDamage** [comment]
im bored imma do a worthless pr on helpme

**Pull request closed without merging**
